<?php

namespace Database\Seeders;

use App\Models\Species;
use App\Models\Tree;
use App\Models\TreeCategory;
use App\Models\TreeStock;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TreeSeeder extends Seeder
{
    public function run(): void
    {
        $trees = [
            [
                'common_name' => 'Outeniqua Yellowwood',
                'botanical_name' => 'Afrocarpus falcatus',
                'category_slug' => 'indigenous-trees',
                'species_slug' => 'afrocarpus-falcatus',
                'is_indigenous' => true,
                'is_evergreen' => true,
                'sizes' => ['500L', '1000L'],
            ],
            [
                'common_name' => 'Tree Aloe',
                'botanical_name' => 'Aloe barberae',
                'category_slug' => 'indigenous-trees',
                'species_slug' => 'aloe-barberae',
                'is_indigenous' => true,
                'is_evergreen' => true,
                'sizes' => ['250L', '500L', '1000L', '2000L'],
            ],
            [
                'common_name' => 'Masada Aloe',
                'botanical_name' => 'Aloe masada',
                'category_slug' => 'exotic-trees',
                'species_slug' => 'aloe-masada',
                'is_indigenous' => false,
                'is_evergreen' => true,
                'sizes' => ['250L'],
            ],
            [
                'common_name' => 'Bitter Aloe',
                'botanical_name' => 'Aloe ferox',
                'category_slug' => 'indigenous-trees',
                'species_slug' => 'aloe-ferox',
                'is_indigenous' => true,
                'is_evergreen' => true,
                'sizes' => ['100L'],
            ],
            [
                'common_name' => 'Dune Aloe',
                'botanical_name' => 'Aloe thraskii',
                'category_slug' => 'indigenous-trees',
                'species_slug' => 'aloe-thraskii',
                'is_indigenous' => true,
                'is_evergreen' => true,
                'sizes' => ['100L'],
            ],
            [
                'common_name' => 'Bougainvillea',
                'botanical_name' => 'Bougainvillea',
                'category_slug' => 'exotic-trees',
                'species_slug' => 'bougainvillea',
                'is_indigenous' => false,
                'is_evergreen' => true,
                'sizes' => ['250L'],
            ],
            [
                'common_name' => 'Coastal Silver Oak',
                'botanical_name' => 'Brachylaena discolor',
                'category_slug' => 'indigenous-trees',
                'species_slug' => 'brachylaena-discolor',
                'is_indigenous' => true,
                'is_evergreen' => true,
                'sizes' => ['100L'],
            ],
            [
                'common_name' => 'Chinese Hackberry',
                'botanical_name' => 'Celtis sinensis',
                'category_slug' => 'deciduous-trees',
                'species_slug' => 'celtis-sinensis',
                'is_indigenous' => false,
                'is_evergreen' => false,
                'sizes' => ['250L', '500L', '1000L'],
            ],
            [
                'common_name' => 'Carob Tree',
                'botanical_name' => 'Ceratonia siliqua',
                'category_slug' => 'exotic-trees',
                'species_slug' => 'ceratonia-siliqua',
                'is_indigenous' => false,
                'is_evergreen' => true,
                'sizes' => ['1000L'],
            ],
            [
                'common_name' => 'Silk Floss Tree',
                'botanical_name' => 'Chorisa speciosa',
                'category_slug' => 'exotic-trees',
                'species_slug' => 'chorisa-speciosa',
                'is_indigenous' => false,
                'is_evergreen' => false,
                'sizes' => ['1000L'],
            ],
            [
                'common_name' => 'Eureka Lemon',
                'botanical_name' => 'Citrus limon Eureka',
                'category_slug' => 'exotic-trees',
                'species_slug' => 'citrus-limon-eureka',
                'is_indigenous' => false,
                'is_evergreen' => true,
                'sizes' => ['250L'],
            ],
            [
                'common_name' => 'Italian Cypress',
                'botanical_name' => 'Cupressus sempervirens Stricta',
                'category_slug' => 'exotic-trees',
                'species_slug' => 'cupressus-sempervirens-stricta',
                'is_indigenous' => false,
                'is_evergreen' => true,
                'sizes' => ['250L', '500L'],
            ],
            [
                'common_name' => 'Leyland Cypress',
                'botanical_name' => 'Cupressus x leylandii',
                'category_slug' => 'exotic-trees',
                'species_slug' => 'cupressus-x-leylandii',
                'is_indigenous' => false,
                'is_evergreen' => true,
                'sizes' => ['250L'],
            ],
            [
                'common_name' => 'Forest Bushwillow',
                'botanical_name' => 'Combretum kraussii',
                'category_slug' => 'indigenous-trees',
                'species_slug' => 'combretum-kraussii',
                'is_indigenous' => true,
                'is_evergreen' => false,
                'sizes' => ['250L'],
            ],
            [
                'common_name' => 'Flamboyant Tree',
                'botanical_name' => 'Delonix regia',
                'category_slug' => 'flowering-trees',
                'species_slug' => 'delonix-regia',
                'is_indigenous' => false,
                'is_evergreen' => false,
                'sizes' => ['100L'],
            ],
            [
                'common_name' => 'Cape Ash',
                'botanical_name' => 'Ekebergia capensis',
                'category_slug' => 'indigenous-trees',
                'species_slug' => 'ekebergia-capensis',
                'is_indigenous' => true,
                'is_evergreen' => true,
                'sizes' => ['100L', '250L'],
            ],
            [
                'common_name' => 'Coast Coral Tree',
                'botanical_name' => 'Erythrina caffra',
                'category_slug' => 'indigenous-trees',
                'species_slug' => 'erythrina-caffra',
                'is_indigenous' => true,
                'is_evergreen' => false,
                'sizes' => ['100L', '500L', '1000L', '2000L'],
            ],
            [
                'common_name' => 'Natal Fig',
                'botanical_name' => 'Ficus natalensis',
                'category_slug' => 'indigenous-trees',
                'species_slug' => 'ficus-natalensis',
                'is_indigenous' => true,
                'is_evergreen' => true,
                'sizes' => ['250L', '500L', '1000L'],
            ],
            [
                'common_name' => 'Port Jackson Fig',
                'botanical_name' => 'Ficus rubiginosa',
                'category_slug' => 'exotic-trees',
                'species_slug' => 'ficus-rubiginosa',
                'is_indigenous' => false,
                'is_evergreen' => true,
                'sizes' => ['250L', '500L', '1000L', '2000L'],
            ],
            [
                'common_name' => 'Jacaranda',
                'botanical_name' => 'Jacaranda mimosifolia',
                'category_slug' => 'flowering-trees',
                'species_slug' => 'jacaranda-mimosifolia',
                'is_indigenous' => false,
                'is_evergreen' => false,
                'sizes' => ['500L'],
            ],
            [
                'common_name' => 'Wild Plum',
                'botanical_name' => 'Harpephyllum caffrum',
                'category_slug' => 'indigenous-trees',
                'species_slug' => 'harpephyllum-caffrum',
                'is_indigenous' => true,
                'is_evergreen' => true,
                'sizes' => ['100L', '1000L'],
            ],
            [
                'common_name' => 'Chinese Juniper',
                'botanical_name' => 'Juniperus chinensis',
                'category_slug' => 'exotic-trees',
                'species_slug' => 'juniperus-chinensis',
                'is_indigenous' => false,
                'is_evergreen' => true,
                'sizes' => ['100L', '250L'],
            ],
            [
                'common_name' => 'Crape Myrtle',
                'botanical_name' => 'Lagerstroemia indica',
                'category_slug' => 'flowering-trees',
                'species_slug' => 'lagerstroemia-indica',
                'is_indigenous' => false,
                'is_evergreen' => false,
                'sizes' => ['250L', '2000L'],
            ],
            [
                'common_name' => 'Sweetgum',
                'botanical_name' => 'Liquidambar styraciflua',
                'category_slug' => 'deciduous-trees',
                'species_slug' => 'liquidambar-styraciflua',
                'is_indigenous' => false,
                'is_evergreen' => false,
                'sizes' => ['500L'],
            ],
            [
                'common_name' => 'Peach Mango',
                'botanical_name' => 'Mangifera peach',
                'category_slug' => 'exotic-trees',
                'species_slug' => 'mangifera-peach',
                'is_indigenous' => false,
                'is_evergreen' => true,
                'sizes' => ['100L'],
            ],
            [
                'common_name' => 'Forest Elder',
                'botanical_name' => 'Nuxia floribunda',
                'category_slug' => 'indigenous-trees',
                'species_slug' => 'nuxia-floribunda',
                'is_indigenous' => true,
                'is_evergreen' => true,
                'sizes' => ['100L', '250L'],
            ],
            [
                'common_name' => 'Frantoio Olive',
                'botanical_name' => 'Olea europaea Frantoio',
                'category_slug' => 'exotic-trees',
                'species_slug' => 'olea-europaea-frantoio',
                'is_indigenous' => false,
                'is_evergreen' => true,
                'sizes' => ['100L', '250L', '500L'],
            ],
            [
                'common_name' => 'Mission Olive',
                'botanical_name' => 'Olea europaea Mission',
                'category_slug' => 'exotic-trees',
                'species_slug' => 'olea-europaea-mission',
                'is_indigenous' => false,
                'is_evergreen' => true,
                'sizes' => ['100L', '250L'],
            ],
            [
                'common_name' => 'Wild Olive',
                'botanical_name' => 'Olea europaea subsp. africana',
                'category_slug' => 'indigenous-trees',
                'species_slug' => 'olea-europaea-subsp-africana',
                'is_indigenous' => true,
                'is_evergreen' => true,
                'sizes' => ['100L', '250L', '500L', '1000L'],
            ],
            [
                'common_name' => 'London Plane',
                'botanical_name' => 'Platanus x acerifolia',
                'category_slug' => 'deciduous-trees',
                'species_slug' => 'platanus-x-acerifolia',
                'is_indigenous' => false,
                'is_evergreen' => false,
                'sizes' => ['100L', '250L', '500L', '1000L'],
            ],
            [
                'common_name' => 'Frangipani',
                'botanical_name' => 'Plumeria rubra',
                'category_slug' => 'flowering-trees',
                'species_slug' => 'plumeria-rubra',
                'is_indigenous' => false,
                'is_evergreen' => false,
                'sizes' => ['250L'],
            ],
            [
                'common_name' => 'Simon Poplar',
                'botanical_name' => 'Populus simonii',
                'category_slug' => 'deciduous-trees',
                'species_slug' => 'populus-simonii',
                'is_indigenous' => false,
                'is_evergreen' => false,
                'sizes' => ['100L', '200L', '250L', '500L'],
            ],
            [
                'common_name' => 'English Oak',
                'botanical_name' => 'Quercus robur',
                'category_slug' => 'deciduous-trees',
                'species_slug' => 'quercus-robur',
                'is_indigenous' => false,
                'is_evergreen' => false,
                'sizes' => ['1000L'],
            ],
            [
                'common_name' => 'Cork Oak',
                'botanical_name' => 'Quercus suber',
                'category_slug' => 'exotic-trees',
                'species_slug' => 'quercus-suber',
                'is_indigenous' => false,
                'is_evergreen' => true,
                'sizes' => ['500L'],
            ],
            [
                'common_name' => 'Marula',
                'botanical_name' => 'Sclerocarya birrea',
                'category_slug' => 'indigenous-trees',
                'species_slug' => 'sclerocarya-birrea',
                'is_indigenous' => true,
                'is_evergreen' => false,
                'sizes' => ['100L'],
            ],
            [
                'common_name' => 'White Milkwood',
                'botanical_name' => 'Sideroxylon inerme',
                'category_slug' => 'indigenous-trees',
                'species_slug' => 'sideroxylon-inerme',
                'is_indigenous' => true,
                'is_evergreen' => true,
                'sizes' => ['100L', '250L', '500L', '1000L'],
            ],
            [
                'common_name' => 'Waterberry',
                'botanical_name' => 'Syzygium cordatum',
                'category_slug' => 'indigenous-trees',
                'species_slug' => 'syzygium-cordatum',
                'is_indigenous' => true,
                'is_evergreen' => true,
                'sizes' => ['250L', '1000L'],
            ],
            [
                'common_name' => 'Water Pear',
                'botanical_name' => 'Syzygium guineense',
                'category_slug' => 'indigenous-trees',
                'species_slug' => 'syzygium-guineense',
                'is_indigenous' => true,
                'is_evergreen' => true,
                'sizes' => ['250L', '500L', '1000L'],
            ],
            [
                'common_name' => 'Water Pear (Exotic)',
                'botanical_name' => 'Syzygium paniculatum',
                'category_slug' => 'exotic-trees',
                'species_slug' => 'syzygium-paniculatum',
                'is_indigenous' => false,
                'is_evergreen' => true,
                'sizes' => ['100L'],
            ],
            [
                'common_name' => 'Natal Mahogany',
                'botanical_name' => 'Trichilia emetica',
                'category_slug' => 'indigenous-trees',
                'species_slug' => 'trichillia-emetica',
                'is_indigenous' => true,
                'is_evergreen' => true,
                'sizes' => ['250L', '500L', '1000L'],
            ],
            [
                'common_name' => 'Monkey Thorn',
                'botanical_name' => 'Vachellia galpinii',
                'category_slug' => 'indigenous-trees',
                'species_slug' => 'vachellia-galpinii',
                'is_indigenous' => true,
                'is_evergreen' => false,
                'sizes' => ['250L'],
            ],
            [
                'common_name' => 'Fever Tree',
                'botanical_name' => 'Vachellia xanthophloea',
                'category_slug' => 'indigenous-trees',
                'species_slug' => 'vachellia-xanthophloea',
                'is_indigenous' => true,
                'is_evergreen' => false,
                'sizes' => ['500L'],
            ],
            [
                'common_name' => 'Laurustinus (Chinese)',
                'botanical_name' => 'Viburnum sinensis',
                'category_slug' => 'exotic-trees',
                'species_slug' => 'viburnum-sinensis',
                'is_indigenous' => false,
                'is_evergreen' => true,
                'sizes' => ['250L', '500L'],
            ],
            [
                'common_name' => 'Laurustinus',
                'botanical_name' => 'Viburnum tinus',
                'category_slug' => 'exotic-trees',
                'species_slug' => 'viburnum-tinus',
                'is_indigenous' => false,
                'is_evergreen' => true,
                'sizes' => ['100L', '250L'],
            ],
        ];

        $pricesMap = [
            '100L' => 950.00,
            '200L' => 1800.00,
            '250L' => 2250.00,
            '500L' => 4500.00,
            '1000L' => 9500.00,
            '2000L' => 19500.00,
        ];

        foreach ($trees as $treeData) {
            $category = TreeCategory::where('slug', $treeData['category_slug'])->first();
            $species = Species::where('slug', $treeData['species_slug'])->first();

            if (!$category) {
                continue;
            }

            $tree = Tree::updateOrCreate(
                ['slug' => Str::slug($treeData['common_name'])],
                [
                    'tree_category_id' => $category->id,
                    'species_id' => $species?->id,
                    'common_name' => $treeData['common_name'],
                    'botanical_name' => $treeData['botanical_name'],
                    'slug' => Str::slug($treeData['common_name']),
                    'is_indigenous' => $treeData['is_indigenous'],
                    'is_evergreen' => $treeData['is_evergreen'],
                    'is_active' => true,
                ]
            );

            // Seed stock for this tree
            foreach ($treeData['sizes'] as $size) {
                $price = $pricesMap[$size] ?? 2000.00;
                TreeStock::updateOrCreate(
                    [
                        'tree_id' => $tree->id,
                        'container_size' => $size,
                    ],
                    [
                        'quantity' => rand(20, 200),
                        'price' => $price,
                        'is_available' => true,
                    ]
                );
            }
        }
    }
}
